#!/usr/bin/env python
import rospy
from std_msgs.msg import String
from geometry_msgs.msg import Pose

def pose_publisher():
    pub = rospy.Publisher('initialpose', String, queue_size=10)
    rospy.init_node('pose_publisher', anonymous=True)
    rate = rospy.Rate(5) # 10hz
    p = Pose()
    p.position.x = 0.5
    p.position.y = -0.1
    p.position.z = 1.0
    # Make sure the quaternion is valid and normalized
    p.orientation.x = 0.0
    p.orientation.y = 0.0
    p.orientation.z = 0.0
    p.orientation.w = 1.0

    while count < 5:
        #rospy.loginfo(hello_str)
        pub.publish(hello_str)
        count+=1
        rate.sleep()

if __name__ == '__main__':
    try:
        pose_publisher()
    except rospy.ROSInterruptException:
        pass

